### PR TITLE
Remote audio mute and un-mute fixes

### PR DESCRIPTION
**Pull request by pallab-gain**
Fix for remote audio mute using RtpTransceiver. Previously, even if the speaker is disabled, other parties audio can still be heard.

- https://github.com/somia/mobile/issues/92

### CODE REVIEW

**Comment by pallab-gain** [comment]
FYI -
Just like [https://github.com/somia/mobile/issues/187](https://github.com/somia/mobile/issues/187) issue, this will not solve the UI and media state sync issue. We will fix the UI sync issue separately,

**Comment by tsavola** [comment]
Should feature branches be merged to `develop` first? Or what's the process?

**Comment by pallab-gain** [comment]
@tsavola Yes. I didn't know the process and messed it up. Antti just explained our process in the channel. I am going to fix it.

**Comment by pallab-gain** [comment]
@Toni- I was not following the right process. I just merged the `develop` branch to this current branch( bugfix ), and change the base branch to `develop` and required for your review again. Can you just go through again as well?

**Comment by pallab-gain** [comment]
Update - 
 I will merge this branch today. Please let me know if we have some no.

**Comment by tsavola** [comment]
> Update -
> I will merge this branch today. Please let me know if we have some no.

The problem with multiple reviewers is that nobody is willing to say anything definitive...

**Comment by tsavola** [comment]
Let's see what the round-robin says...

**Comment by tsavola** [comment]
I cleared all reviewers, but it automatically re-added/kept Toni... I tried to add the @somia/android-review group as reviewer, but it doesn't let me. Maybe it added it automatically due to CODEOWNERS?

**Comment by tsavola** [comment]
Oh Toni already approved these changes earlier, and had a yellow dot due to re-review request?

Sorry for the noise.

**Comment by pallab-gain** [comment]
Thank timo for doing extra work and helping me onboard with Github practices :D

**Pull request merged**
